AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Local Backbrace API
Resources:
  BedrockFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 10
      Handler: handler.handler
      Runtime: nodejs18.x
      CodeUri: dist/lambda/javascript/
      Environment:
        Variables:
          IS_LOCAL: true
      Events:
        Api:
          Type: Api
          Properties:
            Path: /bedrock
            Method: post
